coursify/config/routes.rb
Rails.application.routes.draw do

  

  devise_for :student_users, :skip => [:sessions], :controllers => { :registrations => 'student_registrations'}

  as :student_user do
    get 'signin' => 'devise/sessions#new', :as => :new_student_user_session
    post 'signin' => 'devise/sessions#create', :as => :student_user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_student_user_session
  end

  # get 'studentportal/index'

  # get 'studentportal/show'

  # devise_for :admin_users
  devise_for :admin_users, :controllers => { :registrations => 'registrations'}, :skip => [:sessions]

  as :admin_user do
    get 'adminsignin' => 'devise/sessions#new', :as => :new_admin_user_session
    post 'adminsignin' => 'devise/sessions#create', :as => :admin_user_session
    delete 'adminsignout' => 'devise/sessions#destroy', :as => :destroy_admin_user_session
  end
  
  get 'contact/new'
  get 'contact/create'

  # get 'onboard', :to => "pages#onboard", :as => "onboard"
  # put "onboard", :to => "pages#onboard_send"

  match 'onboard' =>  "pages#onboard", :via => :get
  match 'onboard' => 'pages#onboard_send', :via => :post

  get 'studentportal', :to => "studentportal#index", :as => "portal"
  get 'coming_soon', :to => "studentportal#done", :as => "coming_soon"
  get 'next_page', :to => "studentportal#next_page", :as => "next_page"
  get 'portal/:permalink', :to => "studentportal#show"

  # resources :lessons
  # resources :sections
  #get 'pages/dashboard'
  

  match 'enroll' =>  "pages#enroll", :via => :get, as: "enroll"
  match 'enroll' => 'pages#create', :via => :post
  match 'homee' =>  "pages#home", :via => :get, as: "homee"


  match ":controller(/:action(/:id))", :via => [:get, :post]
  

  
  root "pages#index"

  mount Ckeditor::Engine => '/ckeditor'
  

  #admin Routes
  get 'pages/dashboard'

  get 'admin/content', to: "admmin#content", as: "admin"

  post 'admin/section_sort', to: "admin#section_sort", as: "sort_sections"
  post 'admin/lesson_sort', to: "admin#lesson_sort", as: "sort_lessons"

  get 'admin/settings'
  get 'admin/section_show/:id', to: "admin#section_show", as: "showsection"
  get 'admin/section_edit/:id', to: "admin#section_edit", as: "editsection"
  delete "admin/section_destroy/:id", to: "admin#section_destroy", as: "destroysection"
  delete "admin/lesson_destroy/:id", to: "admin#lesson_destroy", as: "destroylesson"


  
end

coursify/app/views/admin/_lesson_form.html.erb
  <%= error_messages_for(@section) %>

  <div class="field display-none">
    <%=f.label(:section_id, "Section")%>
    <%= f.select(:section_id, @sections.map {|s| [s.name, s.id]}) %>
  </div>

   <div class="field">
    <%=f.label(:name, "Title")%>
    <%= f.text_field(:name) %>
    
  </div>

  <div class="field display-none">    
    <%=f.label(:permalink)%>
    <%= f.text_field(:permalink) %>    
  </div>

  <div class="field" >
	<%= f.cktext_area :body, :ckeditor => { :toolbar => 'Lessonbody'}%>  	
  </div>




   <div class="field display-none">
    
   <%= f.select(:position, 1..@lesson_count, :selected => @lesson_position) %></td>
  </div>

coursify/app/views/admin/_section_form.html.erb
  <%= error_messages_for(@section) %>

  <div class="field">
    <%=f.label(:name, "Name")%>
    <%= f.text_field(:name) %>
  </div>

   <div class="field display-none">
    
    <%= f.select(:position, 1..@section_count, :selected => @section_position) %>
  </div>

coursify/app/views/admin/content.html.erb
<div class="" style="height: 100%;" >


<div style="position: fixed; width: 100%;" class="portal-header" >
  <div class="hdr2" ></div>
    <div class="navigation-bar" >
    <h1 class="logo" > <span onclick="myFunction()"  class="hide-for-medium-up" ><%= fa_icon "bars" %></span> <a href="/" class="show-for-medium-up" style="color: #fff" ><span  >Coursify</span></a></h1>
      <div class="main-nav" >
  <ul class="navright" >
      <div class="last">

              <li>            
                
                <a href="#" data-dropdown="drop" data-options="align:left;"><%= fa_icon "user" %> <%= current_admin_user.name %></a>

                <ul id="drop" class="f-dropdown" data-dropdown-content>
        <li>
             <a href="/admin_users/edit" style="text-transform: capitalize;">Edit Profile</a>
        </li>
        <li><a data-method="delete" href="/signout" rel="nofollow" style="text-transform: capitalize;">Sign Out</a></li>
      </ul> 
              </li>
            </div>
         </ul>
      </div>

    </div>



  </div>



  <div class="portal-show-body row" style="height: 100%; padding-top: 65px; " >
  <div class="portal-nav medium-3 columns show-for-medium-up " id="toggle-menu"   >

      <ul class="curriculum-ul" >
        <span id='this'></span>
        <li class="curriculum-section-heading  first-heading" >
          <%= link_to "+ Add New Section" , {:controller => 'admin', :action => 'section_new'}, class: "button expand"  %>
        </li>
      </ul>

       <ul class="curriculum-ul" id="sections" data-update-url="<%= sort_sections_url %>">
       



        <% @sections.each do |section|  %>
         

          
                    
           
          <li id="section_<%= section.id %>" class="curriculum-section-heading admin-sections-nav <%= current_page?("/admin/section_show/#{section.id}")? "thisbg" : " " %>" > 
                <span class="handle" ><%= fa_icon "bars" %> </span>
                <%= link_to "#{section.name}", :controller => 'admin', :action => 'section_show',:id => section.id %> </li>
          
        <% end %>
          
        </ul>
    </div>
    <div class="medium-9 columns" >
       <div class="portal-content-block" >

       <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert style="margin:4px; margin-bottom:12px;" class="alert-box radius success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %> 

          <h3 class="text-left"  >Welcome to Coursify.</h3>
        
            <hr>
          <p>Watch the video below to learn how to use Coursify</p>

          <div style="padding-bottom: 460px;" class="flex-video" >       
            <iframe src="//fast.wistia.net/embed/iframe/5fctjq367b?videoFoam=true" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="640" height="360"></iframe><script src="//fast.wistia.net/assets/external/E-v1.js"></script>
          </div>

        
         
       </div>

    </div>
    </div>
</div>

coursify/app/views/admin/lesson_edit.html.erb
<div class="" style="height: 100%;" >


<div style="position: fixed; width: 100%;" class="portal-header" >
  <div class="hdr2" ></div>
    <div class="navigation-bar" >
    <h1 class="logo" > <span onclick="myFunction()"  class="hide-for-medium-up" ><%= fa_icon "bars" %></span> <a href="/" class="show-for-medium-up" style="color: #fff" ><span  >Coursify</span></a></h1>
      <div class="main-nav" >
  <ul class="navright" >
      <div class="last">

              <li>            
                
                <a href="#" data-dropdown="drop" data-options="align:left;"><%= fa_icon "user" %> <%= current_admin_user.name %></a>

                <ul id="drop" class="f-dropdown" data-dropdown-content>
        <li>
             <a href="/admin_users/edit" style="text-transform: capitalize;">Edit Profile</a>
        </li>
        <li><a data-method="delete" href="/signout" rel="nofollow" style="text-transform: capitalize;">Sign Out</a></li>
      </ul> 
              </li>
            </div>
         </ul>
      </div>

    </div>



  </div>



  <div class="portal-show-body row" style="height: 100%; padding-top: 65px; " >
  <div class="portal-nav medium-3 columns show-for-medium-up " id="toggle-menu"   >




      <ul class="curriculum-ul" >
        <span id='this'></span>
        <li class="curriculum-section-heading  first-heading" ><%= link_to "+ Add New Section" , {:controller => 'admin', :action => 'section_new'}, class: "button expand"  %></li>
      </ul>

       <ul class="curriculum-ul" id="sections" data-update-url="<%= sort_sections_url %>">
    


        <% @sections.each do |section|  %>
         

          
                    
                        
          <li id="section_<%= section.id %>" class="curriculum-section-heading admin-sections-nav <%= current_page?("/admin/section_show/#{section.id}")? "thisbg" : " " %>" > 
                <span class="handle" ><%= fa_icon "bars" %> </span>
                <%= link_to "#{section.name}", :controller => 'admin', :action => 'section_show',:id => section.id %></li>
                            
          
          
        <% end %>
          
        </ul>
    </div>
    <div class="medium-9 columns" >
     
       <div class="portal-content-block" >

           <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert style="margin:4px; margin-bottom:12px;" class="alert-box radius success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %> 
     	<div  ><%= link_to "Back to Lessons for Section #{@section.position}", {:action => "section_show", :id => @section.id}, class: "expand radius
                button  float-right", style: "margin-top: 0; margin-bottom: 10px; padding-left: 10px; padding-right: 10px;" %></div>

                

                

        	 
            <hr>

           <ul class="curriculum-ul">
		           <li class="curriculum-section-heading admin-section-nav" > Editing:  <%= @lesson.name %> <%= link_to "Delete" , {:controller => 'admin', :action => 'lesson_destroy', :id => @lesson.id, :section_id => @section.id}, method: :delete, data: { confirm: "Are you sure?" }, class: "destroy-button  float-right"  %></li>
		            <li class="curriculum-section-form" >
                  

                <%= form_for(:lesson, url: {action: "lesson_update", :id => @lesson.id, :section_id => @section.id}) do |f| %>

                  <%= render(:partial => "lesson_form", :locals => {:f => f}) %>
                      
                  <%= f.check_box(:visible, :style => 'visibility: hidden') %>



                    <div class="actions">
                       <%= f.submit "Update Lesson",  :style => 'background-color:rgb(216, 38, 46);' , :class => "button expand success large radius" %>
                    </div>

                <% end %>
                
                </li>
        	</ul>
         
       </div>

    </div>
    </div>
</div>

coursify/app/views/admin/lesson_new.html.erb
<div class="" style="height: 100%;" >


<div style="position: fixed; width: 100%;" class="portal-header" >
  <div class="hdr2" ></div>
    <div class="navigation-bar" >
    <h1 class="logo" > <span onclick="myFunction()"  class="hide-for-medium-up" ><%= fa_icon "bars" %></span> <a href="/" class="show-for-medium-up" style="color: #fff" ><span  >Coursify</span></a></h1>
      <div class="main-nav" >
  <ul class="navright" >
      <div class="last">

              <li>            
                
                <a href="#" data-dropdown="drop" data-options="align:left;"><%= fa_icon "user" %> <%= current_admin_user.name %></a>

                <ul id="drop" class="f-dropdown" data-dropdown-content>
        <li>
            <a href="/admin_users/edit" style="text-transform: capitalize;">Edit Profile</a>
        </li>
        <li><a data-method="delete" href="/signout" rel="nofollow" style="text-transform: capitalize;">Sign Out</a></li>
      </ul> 
              </li>
            </div>
         </ul>
      </div>

    </div>



  </div>



  <div class="portal-show-body row" style="height: 100%; padding-top: 65px; " >
  <div class="portal-nav medium-3 columns show-for-medium-up " id="toggle-menu"   >




       <ul class="curriculum-ul" >
          <span id='this'></span>
            <li class="curriculum-section-heading  first-heading" ><%= link_to "+ Add New Section" , {:controller => 'admin', :action => 'section_new'}, class: "button expand"  %></li>
      </ul>

       <ul class="curriculum-ul" id="sections" data-update-url="<%= sort_sections_url %>">

   



        <% @sections.each do |section|  %>
         

          
                    
                    
          <li id="section_<%= section.id %>" class="curriculum-section-heading admin-sections-nav <%= current_page?("/admin/section_show/#{section.id}")? "thisbg" : " " %>" > 
                <span class="handle" ><%= fa_icon "bars" %> </span>
                <%= link_to "#{section.name}", :controller => 'admin', :action => 'section_show',:id => section.id %> </li>
                     
          
          
        <% end %>
          
        </ul>
    </div>
    <div class="medium-9 columns" >
     
       <div class="portal-content-block" >

           <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert style="margin:4px; margin-bottom:12px;" class="alert-box radius success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %> 
     	<div  ><%= link_to "Back to Lessons for Section #{@section.position}", {:action => "section_show", :id => @section.id}, class: "expand radius
                button  float-right", style: "margin-top: 0; margin-bottom: 10px; padding-left: 10px; padding-right: 10px;" %></div>

                

                

        	 
            <hr>

           <ul class="curriculum-ul">
		           <li class="curriculum-section-heading admin-section-nav" > Create New Lesson</li>
		            <li class="curriculum-section-form" >
                  

                <%= form_for(:lesson, url: {action: "lesson_create", :id => @lesson.id, :section_id => @section.id}) do |f| %>

                  <%= render(:partial => "lesson_form", :locals => {:f => f}) %>
                      
                  <%= f.check_box(:visible, checked: true , :style => 'visibility: hidden') %>



                    <div class="actions">
                       <%= f.submit "Create Lesson",  :style => 'background-color:rgb(216, 38, 46);' , :class => "button expand success large radius" %>
                    </div>

                <% end %>
                
                </li>
        	</ul>
         
       </div>

    </div>
    </div>
</div>

coursify/app/views/admin/section_edit.html.erb
<div class="" style="height: 100%;" >


<div style="position: fixed; width: 100%;" class="portal-header" >
  <div class="hdr2" ></div>
    <div class="navigation-bar" >
    <h1 class="logo" > <span onclick="myFunction()"  class="hide-for-medium-up" ><%= fa_icon "bars" %></span> <a href="/" class="show-for-medium-up" style="color: #fff" ><span  >Coursify</span></a></h1>
      <div class="main-nav" >
  <ul class="navright" >
      <div class="last">

              <li>            
                
                <a href="#" data-dropdown="drop" data-options="align:left;"><%= fa_icon "user" %> <%= current_admin_user.name %></a>

                <ul id="drop" class="f-dropdown" data-dropdown-content>
        <li>
             <a href="/admin_users/edit" style="text-transform: capitalize;">Edit Profile</a>
        </li>
        <li><a data-method="delete" href="/signout" rel="nofollow" style="text-transform: capitalize;">Sign Out</a></li>
      </ul> 
              </li>
            </div>
         </ul>
      </div>

    </div>



  </div>



  <div class="portal-show-body row" style="height: 100%; padding-top: 65px; " >
  <div class="portal-nav medium-3 columns show-for-medium-up " id="toggle-menu"   >



      <ul class="curriculum-ul" >
            <span id='this'></span>
             <li class="curriculum-section-heading  first-heading" ><%= link_to "+ Add New Section" , {:controller => 'admin', :action => 'section_new'}, class: "button expand"  %></li>
      </ul>

       <ul class="curriculum-ul" id="sections" data-update-url="<%= sort_sections_url %>">

      



        <% @sections.each do |section|  %>
         

          
                    
            
                
                
                <li id="section_<%= section.id %>" class="curriculum-section-heading admin-sections-nav <%= current_page?("/admin/section_show/#{section.id}")? "thisbg" : " " %>" > 
                <span class="handle" ><%= fa_icon "bars" %> </span>
                <%= link_to "#{section.name}", :controller => 'admin', :action => 'section_show',:id => section.id %> </li>

          
          
        <% end %>
          
        </ul>
    </div>
    <div class="medium-9 columns" >
     
       <div class="portal-content-block" >

           <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert style="margin:4px; margin-bottom:12px;" class="alert-box radius success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %> 
     	<div  ><%= link_to "Back to Section #{@section.position}", {:action => "section_show", :id => @section.id}, class: "expand radius
                button  float-right", style: "margin-top: 0; margin-bottom: 10px; padding-left: 10px; padding-right: 10px;" %></div>

        	 
            <hr>

           <ul class="curriculum-ul">
		           <li class="curriculum-section-heading admin-section-nav" > Edit:  <%= @section.name %> </li>
		            <li class="curriculum-section-form" >
                  

                
                <%= form_for(:section, url: {action: "section_update", :id => @section.id}) do |f| %>

                  <%= render(:partial => "section_form", :locals => {:f => f}) %>
                      <%= f.check_box(:visible, :style => 'visibility: hidden') %>



                    <div class="actions">
                       <%= f.submit "Update Section",  :style => 'background-color:rgb(216, 38, 46);' , :class => "button expand success large radius" %>
                    </div>

                <% end %>
                </li>
        	</ul>
         
       </div>

    </div>
    </div>
</div>

coursify/app/views/admin/section_new.html.erb
<% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert style="margin:4px; margin-bottom:12px;" class="alert-box radius success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %> 

<div class="" style="height: 100%;" >


<div style="position: fixed; width: 100%;" class="portal-header" >
  <div class="hdr2" ></div>
    <div class="navigation-bar" >
    <h1 class="logo" > <span onclick="myFunction()"  class="hide-for-medium-up" ><%= fa_icon "bars" %></span> <a href="/" class="show-for-medium-up" style="color: #fff" ><span  >Coursify</span></a></h1>
      <div class="main-nav" >
  <ul class="navright" >
      <div class="last">

              <li>            
                
                <a href="#" data-dropdown="drop" data-options="align:left;"><%= fa_icon "user" %> <%= current_admin_user.name %></a>

                <ul id="drop" class="f-dropdown" data-dropdown-content>
        <li>
             <a href="/admin_users/edit" style="text-transform: capitalize;">Edit Profile</a>
        </li>
        <li><a data-method="delete" href="/signout" rel="nofollow" style="text-transform: capitalize;">Sign Out</a></li>
      </ul> 
              </li>
            </div>
         </ul>
      </div>

    </div>



  </div>



  <div class="portal-show-body row" style="height: 100%; padding-top: 65px; " >
  <div class="portal-nav medium-3 columns show-for-medium-up " id="toggle-menu"   >




       <ul class="curriculum-ul" >
            <span id='this'></span>
              <li class="curriculum-section-heading  first-heading" ><%= link_to "+ Add New Section" , {:controller => 'admin', :action => 'section_new'}, class: "button expand"  %></li>
      </ul>

       <ul class="curriculum-ul" id="sections" data-update-url="<%= sort_sections_url %>">

      


        <% @sections.each do |section|  %>
         

          
                    
                    
          <li id="section_<%= section.id %>" class="curriculum-section-heading admin-sections-nav <%= current_page?("/admin/section_show/#{section.id}")? "thisbg" : " " %>" > 
                <span class="handle" ><%= fa_icon "bars" %> </span>
                <%= link_to "#{section.name}", :controller => 'admin', :action => 'section_show',:id => section.id %></li>
                   
          
          
        <% end %>
          
        </ul>
    </div>
    <div class="medium-9 columns" >
       <div class="portal-content-block" >

          
     

           <ul class="curriculum-ul">
		           <li class="curriculum-section-heading admin-section-nav" > New Section</li>
		            <li class="curriculum-section-form" >
                   <%= form_for(:section, url: {action: "section_create", :id => @section.id}) do |f| %>

                  <%= render(:partial => "section_form", :locals => {:f => f}) %>

                      <%= f.check_box(:visible, checked: true, :style => 'visibility: hidden') %>



                    <div class="actions">
                       <%= f.submit "Create Section",  :style => 'background-color:rgb(216, 38, 46);' , :class => "button expand success large radius" %>
                    </div>


                <% end %>
                </li>
        	</ul>
         
       </div>

    </div>
    </div>
</div>

coursify/app/views/admin/section_show.html.erb
<div class="" style="height: 100%;" >


<div style="position: fixed; width: 100%;" class="portal-header" >
  <div class="hdr2" ></div>
    <div class="navigation-bar" >
    <h1 class="logo" > <span onclick="myFunction()"  class="hide-for-medium-up" ><%= fa_icon "bars" %></span> <a href="/" class="show-for-medium-up" style="color: #fff" ><span  >Coursify</span></a></h1>
      <div class="main-nav" >
  <ul class="navright" >
      <div class="last">

              <li>            
                
                <a href="#" data-dropdown="drop" data-options="align:left;"><%= fa_icon "user" %> <%= current_admin_user.name %></a>

                <ul id="drop" class="f-dropdown" data-dropdown-content>
        <li>
             <a href="/admin_users/edit" style="text-transform: capitalize;">Edit Profile</a>
        </li>
        <li><a data-method="delete" href="/signout" rel="nofollow" style="text-transform: capitalize;">Sign Out</a></li>
      </ul> 
              </li>
            </div>
         </ul>
      </div>

    </div>



  </div>



  <div class="portal-show-body row" style="height: 100%; padding-top: 65px; " >
  <div class="portal-nav medium-3 columns show-for-medium-up " id="toggle-menu"   >



       <ul class="curriculum-ul" >
            <span id='this'></span>
              <li class="curriculum-section-heading  first-heading" ><%= link_to "+ Add New Section" , {:controller => 'admin', :action => 'section_new'}, class: "button expand"  %></li>
      </ul>


       <ul class="curriculum-ul" id="sections" data-update-url="<%= sort_sections_url %>">

       


        <% @sections.each do |section|  %>
         

          
          <li id="section_<%= section.id %>" class="curriculum-section-heading admin-sections-nav <%= current_page?("/admin/section_show/#{section.id}")? "thisbg" : " " %>" > 
                <span class="handle" ><%= fa_icon "bars" %> </span>
                <%= link_to "#{section.name}", :controller => 'admin', :action => 'section_show',:id => section.id %> </li>
          
          
        <% end %>
          
        </ul>
    </div>
    <div class="medium-9 columns" >
       <div class="portal-content-block" >
       	<% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert style="margin:4px; margin-bottom:12px;" class="alert-box radius success">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %> 
          
     	<div  ><%= link_to " + Add New Lesson", {action: "lesson_new", :section_id => @section.id }, class: "expand radius
                button success float-right", style: "margin-top: 0; margin-bottom: 10px; padding-left: 10px; padding-right: 10px;" %></div>

                

        	 
            <hr>


            <ul class="curriculum-ul" >
             <li  class="curriculum-section-heading admin-section-nav" > <%= @section.name %> <%= link_to "Delete" , {:controller => 'admin', :action => 'section_destroy', :id => @section.id}, method: :delete, data: { confirm: "Are you sure?" }, class: "destroy-button  float-right"  %> <%= link_to "Edit" , {:controller => 'admin', :action => 'section_edit', :id => @section.id}, class: "edit-button  float-right"  %> </li>
           
              </ul>
           <ul class="curriculum-ul" id="lessons" data-update-url="<%= sort_lessons_url %>" >

		       
		              <% @section.lessons.visible.sorted.each do |lesson| %>
		            
		            
		            
		                <li id="lesson_<%= lesson.id %>" class="curriculum-section-item "  > 
		                	<%= link_to  :action => 'lesson_edit', :id => lesson.id, :section_id => lesson.section_id do %>	                

		                <span class="float-left"   ><%= lesson.name %> </span>


		                <!-- <div class="float-right"  ><span  style=" margin:0; padding-top:0; padding-bottom:0; height: 30px; line-height: 30px;"  class="button radius tiny">Start</span></div> -->
		                
		                <% end %> 
                    <span class="handle" ><%= fa_icon "bars" %> </span>
                    <div  class="clear" ></div>

		                </li>
		            
		            <% end %> 
        	</ul>
         
       </div>

    </div>
    </div>
</div>

coursify/app/views/admin/settings.html.erb
<h1>Admin#settings</h1>
<p>Find me in app/views/admin/settings.html.erb</p>